"""
MkDocs hook for the API reference generated by MrDocs (content/api/).

- Builds the navigation of the API reference from the generated pages: a tree of namespaces, types and members, with collapsible sections.
- Shows the API pages with a single sidebar: the page's table of contents is integrated into the navigation (`toc.integrate`), while all other
  pages keep both sidebars.
- Merges duplicate pages of class templates with a `requires` clause. MrDocs (2026.9.4) documents such a class as two symbols: one with the
  complete declaration (template head and constraints) but without members, and one with the members but without the template head. The pages
  are merged into the one with the members, and all links to the other one are redirected.
- Removes the edit button from the API pages, which are generated from the comments in the headers. Each page links to its declaration on
  GitHub instead.
"""

from __future__ import annotations

import posixpath
import re

from mkdocs.structure.files import File, Files
from mkdocs.structure.nav import Navigation, Section
from mkdocs.structure.pages import Page

API_DIR = "api/"
API_INDEX = "api/index.md"
FRONT_MATTER_TITLE = re.compile(r'^title:\s*"?(?P<title>.*?)"?\s*$', re.MULTILINE)
SYNOPSIS = re.compile(r'<pre class="mrdocs-synopsis">.*?</pre>', re.DOTALL)
HREF = re.compile(r'href="(?P<href>[^"#]*)(?P<fragment>#[^"]*)?"')

# Duplicate pages of the current build: the source file of the page that is kept, mapped to the sources of the pages merged into it, and the
# URLs of the merged pages, mapped to the URL of the page that is kept.
MERGES: dict[str, list[str]] = {}
REDIRECTS: dict[str, str] = {}


def is_api_page(uri: str) -> bool:
    return uri.startswith(API_DIR) and uri.endswith(".md")


# ------------------------------------------------------------------------ Files ------------------------------------------------------------------------

def read_head(path: str) -> str:
    try:
        with open(path, encoding="utf-8") as source:
            return source.read(4096)
    except OSError:
        return ""


def is_overload_set(head: str) -> bool:
    """Overview pages of overloaded functions list the synopses of all overloads."""
    return "\n## Synopses" in head


def page_url(src_uri: str) -> str:
    """The URL of a page with directory URLs, e.g. `api/LiteFX/Rendering/Barrier-00/` for `api/LiteFX/Rendering/Barrier-00.md`."""
    stem = src_uri[:-3]
    return (stem[:-len("index")] if stem.endswith("/index") else stem + "/")


def declared_class(head: str, title: str) -> bool:
    """Whether the synopsis of a page declares a class, struct or union with the given name (as opposed to e.g. overloaded functions)."""
    synopsis = SYNOPSIS.search(head)
    name = re.escape(re.split(r"::(?![^<]*>)", title)[-1])
    return bool(synopsis and re.search(rf"\b(class|struct|union)\s+{name}\b", synopsis.group(0)))


def find_duplicates(api_files: list[File], directories: set[str]) -> None:
    """Finds classes that are documented on multiple pages in the same scope (see module documentation)."""
    MERGES.clear()
    REDIRECTS.clear()
    groups: dict[tuple[str, str], list[tuple[File, str]]] = {}

    for file in api_files:
        head = read_head(file.abs_src_path)
        match = FRONT_MATTER_TITLE.search(head)

        if match and not is_overload_set(head) and declared_class(head, match.group("title")):
            groups.setdefault((file.src_uri.rsplit("/", 1)[0], match.group("title")), []).append((file, head))

    for pages in groups.values():
        if len(pages) < 2:
            continue

        # Keep the page with the members (it has a directory with their pages). Pages that have members themselves are never merged.
        with_members = [p for p in pages if p[0].src_uri[:-3] in directories]

        if len(with_members) > 1:
            continue

        kept = with_members[0] if with_members else next((p for p in pages if "requires" in p[1]), pages[0])

        for file, _ in pages:
            if file is not kept[0]:
                MERGES.setdefault(kept[0].src_uri, []).append(file.abs_src_path)
                REDIRECTS[page_url(file.src_uri)] = page_url(kept[0].src_uri)


def on_files(files: Files, config, **kwargs) -> Files:
    """Turns pages that get their own section in the navigation into index pages: namespaces and types (e.g. `api/LiteFX/Rendering/IImage.md`
    becomes `api/LiteFX/Rendering/IImage/index.md`), and overview pages of overloaded functions. This way, they become the clickable titles of
    their sections. The URL of the pages does not change, so links between the generated pages remain valid."""
    api_files = [f for f in files if is_api_page(f.src_uri) and f.src_uri != API_INDEX]
    directories = {f.src_uri.rsplit("/", 1)[0] for f in api_files}

    # Remove duplicate pages, which are merged into the page that is kept (see `on_page_markdown`).
    find_duplicates(api_files, directories)
    merged = {path for paths in MERGES.values() for path in paths}

    for file in [f for f in api_files if f.abs_src_path in merged]:
        files.remove(file)
        api_files.remove(file)

    for file in api_files:
        stem = file.src_uri[:-3]

        if file.src_uri.endswith("/index.md"):
            continue

        if stem in directories or is_overload_set(read_head(file.abs_src_path)):
            files.remove(file)
            files.append(File.generated(config, f"{stem}/index.md", abs_src_path=file.abs_src_path))

            if file.src_uri in MERGES:
                MERGES[f"{stem}/index.md"] = MERGES.pop(file.src_uri)

    return files


# ---------------------------------------------------------------------- Navigation ---------------------------------------------------------------------

def read_symbol(file: File) -> tuple[str, bool, bool]:
    """Returns the unqualified name of the symbol a page documents (e.g. `IImage` for `LiteFX::Rendering::IImage`), whether it is a
    namespace (the only pages without a declaration), and whether it is the overview page of an overloaded function."""
    head = read_head(file.abs_src_path)
    match = FRONT_MATTER_TITLE.search(head)
    name = match.group("title") if match else file.name

    # Split at `::`, but not within template arguments (e.g. `Foo<A::B>`).
    return re.split(r"::(?![^<]*>)", name)[-1] or name, "Declared in" not in head, is_overload_set(head)


def sort_key(node: dict) -> tuple:
    """Namespaces first, then constructors and destructors, then all other symbols alphabetically. Overloads keep their order."""
    stem = node["stem"].rsplit("/", 1)[-1]

    if node["namespace"]:
        group = 0
    elif stem.startswith("2constructor"):
        group = 1
    elif stem.startswith("2destructor"):
        group = 2
    else:
        group = 3

    return group, node["title"].lower(), stem


def label(title: str, constructor: bool, number: int | None) -> str:
    """Constructors are named like their class, so they are labeled explicitly. Overloads are numbered."""
    suffix = " ".join(part for part in ("constructor" if constructor else "", str(number) if number else "") if part)
    return f"{title} ({suffix})" if suffix else title


def build_items(node: dict) -> list:
    items = []
    children = sorted(node["children"].values(), key=sort_key)

    # Group the children by name: overloads share a name, and are shown below their overview page (if there is one).
    groups: dict[str, list] = {}

    for child in children:
        groups.setdefault(child["title"], []).append(child)

    for title, members in groups.items():
        overview = next((m for m in members if m["overloads"]), None)
        overloads = [m for m in members if m is not overview]
        constructor = members[0]["stem"].rsplit("/", 1)[-1].startswith("2constructor")

        if overview is not None:
            page = overview["file"].page
            page.title = label(title, constructor, None)
            section_items = [page]

            for number, overload in enumerate(overloads, start=1):
                overload["file"].page.title = label(title, constructor, number)
                section_items.append(overload["file"].page)

            items.append(Section(page.title, section_items))
            continue

        for number, member in enumerate(members, start=1):
            page = member["file"].page if member["file"] else None
            item_title = label(title, constructor, number if len(members) > 1 else None)

            if page:
                page.title = item_title

            if member["children"]:
                items.append(Section(item_title, ([page] if page else []) + build_items(member)))
            elif page:
                items.append(page)

    return items


def set_parents(items: list, parent) -> None:
    for item in items:
        item.parent = parent

        if isinstance(item, Section):
            set_parents(item.children, item)


def find_api_index(items: list, parent=None):
    for index, item in enumerate(items):
        if isinstance(item, Page) and item.file.src_uri == API_INDEX:
            return items, index, parent

        if isinstance(item, Section):
            found = find_api_index(item.children, item)

            if found:
                return found

    return None


def all_pages(items: list):
    for item in items:
        if isinstance(item, Page):
            yield item
        elif isinstance(item, Section):
            yield from all_pages(item.children)


def on_nav(nav: Navigation, config, files: Files, **kwargs) -> Navigation:
    """Replaces the API reference entry of the navigation with a tree of the generated pages."""
    found = find_api_index(nav.items)

    if found is None:
        return nav

    container, index, parent = found
    api_index = container[index]

    # Build a tree from the page paths: `api/LiteFX/Rendering/IImage/index.md` is the node `LiteFX/Rendering/IImage`.
    root: dict = {"stem": "", "title": "", "file": None, "namespace": True, "overloads": False, "children": {}}

    for file in files.documentation_pages():
        uri = file.src_uri

        if not is_api_page(uri) or uri == API_INDEX:
            continue

        stem = uri[len(API_DIR):-3]
        stem = stem[:-len("/index")] if stem.endswith("/index") else stem
        node = root

        for part in stem.split("/"):
            node = node["children"].setdefault(part, {"stem": "", "title": part, "file": None, "namespace": False, "overloads": False,
                                                      "children": {}})

        node["stem"] = stem
        node["file"] = file
        node["title"], node["namespace"], node["overloads"] = read_symbol(file)

    section = Section(api_index.title or "API Reference", [api_index] + build_items(root))
    container[index] = section
    set_parents([section], parent)

    # Update the previous/next links and the page list, so that they include the API pages.
    pages = list(all_pages(nav.items))

    for previous, current in zip([None] + pages[:-1], pages):
        current.previous_page = previous

        if previous:
            previous.next_page = current

    if pages:
        pages[-1].next_page = None

    return Navigation(nav.items, pages)


# ------------------------------------------------------------------------ Pages ------------------------------------------------------------------------

def split_sections(markdown: str) -> tuple[str, list[str]]:
    """Splits a page into the part before the first section and its sections (each starting with a `## ` heading)."""
    parts = re.split(r"(?m)^(?=## )", markdown)
    return parts[0], parts[1:]


def heading(section: str) -> str:
    return section.split("\n", 1)[0].strip()


def merge_page(markdown: str, duplicates: list[str]) -> str:
    """Merges the pages of duplicate symbols into a page: the complete declaration (with template head and constraints) replaces the
    incomplete one, and sections that only the duplicates have are added."""
    preamble, sections = split_sections(markdown)

    for path in duplicates:
        with open(path, encoding="utf-8") as source:
            _, duplicate_sections = split_sections(source.read())

        for section in duplicate_sections:
            title = heading(section)
            existing = next((i for i, s in enumerate(sections) if heading(s) == title), None)

            if existing is None:
                # Add the section before "See Also", which is the last section of a page.
                position = next((i for i, s in enumerate(sections) if heading(s) == "## See Also"), len(sections))
                sections.insert(position, section.rstrip("\n") + "\n\n")
            elif title == "## Synopsis":
                complete = SYNOPSIS.search(section)

                if complete and "template&lt;" in complete.group(0) and "template&lt;" not in sections[existing]:
                    sections[existing] = SYNOPSIS.sub(lambda _: complete.group(0), sections[existing], count=1)

    return preamble + "".join(sections)


def redirect_links(markdown: str, page: Page) -> str:
    """Redirects links to merged pages, and removes table rows that are duplicates afterwards (e.g. a class listed twice)."""
    base = page.url or ""

    def replace(match: re.Match) -> str:
        href = match.group("href")

        if not href or "://" in href or href.startswith(("mailto:", "/")):
            return match.group(0)

        target = posixpath.normpath(posixpath.join(base, href)) + "/"

        if target not in REDIRECTS:
            return match.group(0)

        relative = posixpath.relpath(REDIRECTS[target], base or ".") + "/"
        return f'href="{relative}{match.group("fragment") or ""}"'

    lines, seen = [], set()

    for line in HREF.sub(replace, markdown).split("\n"):
        if "<table" in line:
            seen = set()

        if line.startswith("<tr>"):
            if line in seen:
                continue

            seen.add(line)

        lines.append(line)

    return "\n".join(lines)


def on_page_markdown(markdown: str, page: Page, config, files: Files, **kwargs) -> str:
    if not page.file.src_uri.startswith(API_DIR):
        return markdown

    # The pages are generated from the comments in the headers, so there is no source file to edit in the repository.
    page.edit_url = None

    if page.file.src_uri in MERGES:
        markdown = merge_page(markdown, MERGES[page.file.src_uri])

    return redirect_links(markdown, page) if REDIRECTS else markdown


def on_page_context(context, page: Page, config, nav: Navigation, **kwargs):
    # API pages show a single sidebar: their table of contents is integrated into the navigation. The feature is only enabled while the page
    # is rendered (pages are rendered one after another) and is removed again in `on_post_page`.
    if page.file.src_uri.startswith(API_DIR):
        features = config.theme["features"]

        if "toc.integrate" not in features:
            features.append("toc.integrate")
            page.meta["_integrated_toc"] = True

    return context


def on_post_page(output: str, page: Page, config, **kwargs) -> str:
    if page.meta.pop("_integrated_toc", False):
        config.theme["features"].remove("toc.integrate")

    return output
