"""MkDocs hook for the API reference generated by MrDocs (content/api/)."""


def on_page_markdown(markdown, page, config, files, **kwargs):
    # Replace the source file edit URL with a link to the C++ source file on GitHub.
    if page.file.src_uri.startswith("api/"):
        page.edit_url = None

    return markdown
